name: Custom
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SunilKotte/custom-Action@main
      - name: Python Syntax Checker
  # You may pin to the exact commit or the version.
  # uses: class/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          
